modman: link processor.php from Magento to our dir
Replaces #3 (Copy report.php instead of linking it, to avoid relative
path problems with symlinks in require statement)

This avoids the problem when `require_once` in `errors/report.php`
cannot find `processor.php` in our directory and fails with this reason:

  Fatal error: require_once(): Failed opening required 'processor.php'